name: Runt Lint

on: 
  pull_request:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, eslint
      run: |
        npm install
        ./node_modules/.bin/eslint --ext js,vue src/
    - uses: hmarr/auto-approve-action@v2.0.0
      if: success()
      with:
        github-token: "${{ secrets.TOKEN }}"
