name: Runt Lint

on: 
  pull_request:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, eslint
      run: |
        npm install
        ./node_modules/.bin/eslint --ext js,vue src/
    - name: Build 
      if: success()
      run: npm run build
    - name: Commit
      if: success()
      run: |
          git config --global user.name 'M6BOT'
          git config --global user.email 'm6bot@m6connect.com'
          git remote set-url origin https://x-access-token:abcf77ae6d03ece1c62bd557ed00bcb392750c2a@github.com/dafixios/test_actions
          git checkout ${GITHUB_REF#refs/heads/}
          git status
          git add dist
          git commit "AUTOMATIC BUILD"
          git push  
